#version: '3.8'

services:
  # Broker MQTT
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: iot-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001" # websocket
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - iot-network
    restart: always

  # Base de datos InfluxDB (Series Temporales)
  influxdb:
    image: influxdb:2.7
    container_name: iot-influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    environment:
    - DOCKER_INFLUXDB_INIT_MODE=setup
    - DOCKER_INFLUXDB_INIT_USERNAME={INFLUXDB_INIT_USERNAME}
    - DOCKER_INFLUXDB_INIT_PASSWORD={INFLUXDB_INIT_PASSWORD}
    - DOCKER_INFLUXDB_INIT_ORG={INFLUXDB_INIT_ORG}
    - DOCKER_INFLUXDB_INIT_BUCKET={INFLUXDB_INIT_BUCKET}
    - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN={INFLUXDB_INIT_ADMIN_TOKEN}
    networks:
      - iot-network
    restart: always

  # Base de Datos Documental (Usuarios y Alertas)
  mongodb:
    image: mongo:6
    container_name: iot-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - iot-network
    restart: always

  # Node-RED (simulador ESP32 + Backend)
  nodered:
    image: nodered/node-red:latest
    container_name: iot-nodered
    ports:
      - "1880:1880"
    volumes:
      - nodered_data:/data
      - ./node-red/settings.js:/data/settings.js
      - ./dashboard:/data/dashboard
    environment:
      - TZ=Europe/Madrid
    depends_on:
      - mosquitto
      - influxdb
      - mongodb
    networks:
      - iot-network
    restart: always

# visualización Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: iot-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      #- ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SERVER_ROOT_URL=http://localhost:3000
    depends_on:
      - influxdb
    networks:
      - iot-network
    restart: always
volumes:
  mosquitto_data:
  mosquitto_log:
  influxdb_data:
  influxdb_config:
  mongodb_data:
  nodered_data:
  grafana_data:

networks:
  iot-network:
    driver: bridge


