apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: tfm-iot
      defaultBucket: sensor-data-raw
    secureJsonData:
      token: sR9ozJ4plkU1XZeJRm_UH8-3eWADt6FHxuX6u_ws7ruZwxvdRYFfDEwu4OJIo_j7Vnf0_bYago9zlHaqdegTSQ==
    database: iot_data
    user: admin
    password: admin123